// src/lib/schedulerpro-6.3.3-trial/examples-scheduler/frameworks/vue/javascript/dependencies/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
        <bryntum-demo-header />
        <bryntum-scheduler
            ref="scheduler"
            v-bind="schedulerConfig"
        />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader
} from '@bryntum/schedulerpro-vue';
import { schedulerConfig } from './AppConfig';

export default {
    name : 'app',

    components : {
        BryntumDemoHeader,
        BryntumScheduler
    },

    data() {
        return {
            schedulerConfig
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// src/lib/schedulerpro-6.3.3-trial/examples-scheduler/frameworks/react-vite/infinite-scroll-tree/src/App.tsx
import { BryntumDemoHeader, BryntumScheduler } from '@bryntum/schedulerpro-react';
import { schedulerProps } from './AppConfig';
import './App.scss';

const App = () => {
    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <BryntumScheduler
                {...schedulerProps}
            />
        </>
    );
};

export default App;
