// src/lib/schedulerpro-6.3.3-trial/examples/frameworks/vue-3-vite/maps/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { BryntumDemoHeader, BryntumSchedulerPro, BryntumSplitter, BryntumGrid, BryntumSchedulerProProjectModel } from '@bryntum/schedulerpro-vue-3';
import { DateHelper, AssignmentStore } from '@bryntum/schedulerpro';
import type { DateFieldListenersTypes, EventStore, DragHelperConfig, TimeAxis, ProjectModel, SlideToggle, GridListenersTypes, SlideToggleListenersTypes, SchedulerProListenersTypes, FilterFieldListenersTypes, DateField, SubGrid } from '@bryntum/schedulerpro';
import { schedulerProProps, gridProps } from './AppConfig';
import MapPanel from './lib/MapPanel';
import Task from './lib/Task';
import Drag from './lib/Drag';

const schedulerProRef = ref<InstanceType<typeof BryntumSchedulerPro>>();
const gridRef = ref<InstanceType<typeof BryntumGrid>>();
const unplannedSplitterRef = ref<InstanceType<typeof BryntumSplitter>>();
const projectModelRef = ref<InstanceType<typeof BryntumSchedulerProProjectModel>>();

let mapPanel : MapPanel;

// Define event handlers for scheduler components
const onDateFieldChange : DateFieldListenersTypes['change'] = ({ value, userAction }) => {
    if (userAction) {
        const
            startTime = DateHelper.add(value, 8, 'hour'),
            endTime   = DateHelper.add(value, 20, 'hour');

        schedulerProRef.value?.instance.value.setTimeSpan(startTime, endTime);
    }
};

const onNewEventClick = () => {
    const newTask = new schedulerProRef.value.instance.value.eventStore.modelClass({
        startDate : schedulerProRef.value?.instance.value.startDate
    });

    schedulerProRef.value?.instance.value.editEvent(newTask);
};

const onAfterEventSave: SchedulerProListenersTypes['afterEventSave'] = ({ eventRecord }) => {
    const task = eventRecord as Task;
    if (task.marker) {
        mapPanel?.scrollMarkerIntoView(task);
    }
};

const onFilterChange : FilterFieldListenersTypes['change'] = ({ value }) => {
    const escapedValue = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

    schedulerProRef.value?.instance.value.eventStore.filter({
        filters : (event: Task) => new RegExp(escapedValue, 'i').test(event.name),
        replace : true
    });
};

const onToggleUnscheduled: SlideToggleListenersTypes['change'] = ({ value }) => {
    schedulerProRef.value?.instance.value.trigger('toggleUnscheduled', { value });
};

const onEventClick: SchedulerProListenersTypes['eventClick'] = ({ eventRecord }) => {
    const task = eventRecord as Task;
    if (task.marker) {
        mapPanel?.showTooltip(task, true);
    }
};

const onUnplannedSplitterToggle = ({ eventName } : { eventName : string }) => {
    const slideToggle = schedulerProRef.value?.instance.value.widgetMap['toggleUnscheduled'] as SlideToggle;
    slideToggle.value = eventName === 'splitterCollapseClick';
};

const onMarkerClick = async({ eventRecord } : { eventRecord : Task }) => {
    if (eventRecord.resources.length > 0 && schedulerProRef.value?.instance.value) {
        await schedulerProRef.value.instance.value.scrollEventIntoView(eventRecord, { animate : true, highlight : true });
        schedulerProRef.value.instance.value.selectedEvents = [eventRecord];
    }
    else {
        await (gridRef.value?.instance.value as SubGrid).expand(true);
        (schedulerProRef.value?.instance.value.widgetMap['toggleUnscheduled'] as SlideToggle).value = true;
        gridRef.value?.instance.value.scrollRowIntoView(eventRecord, { animate : true, highlight : true });
    }
};

const onCellClick : GridListenersTypes['cellClick'] = ({ record }) => {
    const task = record as Task;
    if (task.marker) {
        mapPanel?.showTooltip(task, true);
    }
};

onMounted(() => {
    mapPanel = new MapPanel({
        ref         : 'map',
        appendTo    : 'content',
        flex        : 2,
        collapsible : true,
        header      : false,
        eventStore  : schedulerProRef.value?.instance.value.eventStore as EventStore,
        timeAxis    : schedulerProRef.value?.instance.value.timeAxis as TimeAxis,
        listeners   : {
            markerclick : onMarkerClick
        }
    });

    const schedulerPro = schedulerProRef.value?.instance.value;
    if (schedulerPro) {
        (schedulerPro.widgetMap['dateField'] as DateField).value = schedulerPro.startDate;
        schedulerPro.widgetMap['dateField'].on('change', onDateFieldChange);
        schedulerPro.widgetMap['newEventButton'].on('click', onNewEventClick);
        schedulerPro.widgetMap['filterByName'].on('change', onFilterChange);
        schedulerPro.widgetMap['toggleUnscheduled'].on('change', onToggleUnscheduled);
        schedulerPro.on('toggleUnscheduled', ({ value } : { value : boolean }) => {
            gridRef.value?.instance.value.toggleCollapsed(!value);
        });

        schedulerPro.project.on('load', ({ source } : { source : ProjectModel }) => {
            if (gridRef.value?.instance.value) {
                gridRef.value.instance.value.store = source.eventStore.chain((eventRecord : Task) => !eventRecord.assignments.length);
                gridRef.value.instance.value.store.sort('name');
            }
        });

        schedulerPro.project.on('change', (props : { store : any, action : string }) => {
            if (props.store instanceof AssignmentStore) {
                if (props.action !== 'dataset') {
                    gridRef.value?.instance.value.store.fillFromMaster();
                }
            }
        });
    }

    const unplannedSplitter = unplannedSplitterRef.value?.instance.value;
    if (unplannedSplitter) {
        unplannedSplitter.on('splitterExpandClick', onUnplannedSplitterToggle);
        unplannedSplitter.on('splitterCollapseClick', onUnplannedSplitterToggle);
    }

    new Drag({
        grid         : gridRef.value?.instance.value,
        schedule     : schedulerProRef.value?.instance.value,
        constrain    : false,
        outerElement : gridRef.value?.instance.value.element
    } as DragHelperConfig);
});
</script>

<template>
    <!-- Bryntum-demo-header is used for Bryntum example only. Not required for application -->
    <bryntum-demo-header />
    <div id="content">
        <bryntum-scheduler-pro
            ref="schedulerProRef"
            :project="projectModelRef"
            v-bind="schedulerProProps"
            @event-click="onEventClick"
            @after-event-save="onAfterEventSave"
        />
        <bryntum-splitter :show-buttons="true" />
    </div>
    <bryntum-splitter
        ref="unplannedSplitterRef"
        :show-buttons="'end'"
    />
    <bryntum-grid
        ref="gridRef"
        v-bind="gridProps"
        @cell-click="onCellClick"
    />
</template>

<style lang="scss">
@import "./App.scss";
</style>

// src/lib/schedulerpro-6.3.3-trial/examples/frameworks/angular/maps/src/app/app.component.ts
import { AfterViewInit, Component, ViewChild, ViewEncapsulation } from '@angular/core';
import { BryntumSchedulerProComponent, BryntumSchedulerProProjectModelComponent, BryntumGridComponent, BryntumSplitterComponent } from '@bryntum/schedulerpro-angular';
import { ButtonListenersTypes, DateField, DateFieldListenersTypes, DateHelper, DragHelperConfig, Grid, GridListenersTypes, ProjectModel, SchedulerPro, SchedulerProListenersTypes, SlideToggle, SlideToggleListenersTypes, Splitter, StoreChainedClass, SubGrid, TextFieldListenersTypes, Toast } from '@bryntum/schedulerpro';
import { projectProps, schedulerProProps, gridProps } from './app.config';
import MapPanel from 'src/lib/MapPanel';
import Task from 'src/lib/Task';
import Drag from 'src/lib/Drag';
import '../assets/vendor/mapbox-gl.js';
import '../lib/AddressSearchField';

@Component({
    selector      : 'app-root',
    templateUrl   : './app.component.html',
    styleUrls     : ['./app.component.scss'],
    encapsulation : ViewEncapsulation.None
})

export class AppComponent implements AfterViewInit {

    projectProps          = projectProps;
    schedulerProProps     = schedulerProProps;
    gridProps             = gridProps;
    tbar                  = [
        {
            text      : 'Add task',
            ref       : 'newEventButton',
            color     : 'b-green b-raised',
            minHeight : '2.5em'
        },
        '->',
        {
            type     : 'datefield',
            ref      : 'dateField',
            width    : 190,
            editable : false,
            step     : 1
        },
        {
            type                 : 'textfield',
            ref                  : 'filterByName',
            placeholder          : 'Filter tasks',
            clearable            : true,
            keyStrokeChangeDelay : 100,
            triggers             : {
                filter : {
                    align : 'start',
                    cls   : 'b-fa b-fa-filter'
                }
            }
        },
        {
            type   : 'slidetoggle',
            ref    : 'toggleUnscheduled',
            label  : 'Show unscheduled',
            height : 'auto'
        }
    ];

    private schedulerPro!: SchedulerPro;
    private project!: ProjectModel;
    private mapPanel!: MapPanel;
    private grid!: Grid;
    private dragHelper!: Drag;
    private unplannedSplitter!: Splitter;
    @ViewChild(BryntumSchedulerProComponent) schedulerProComponent!: BryntumSchedulerProComponent;
    @ViewChild(BryntumSchedulerProProjectModelComponent) projectComponent!: BryntumSchedulerProProjectModelComponent;
    @ViewChild(BryntumGridComponent) gridComponent!: BryntumGridComponent;
    @ViewChild('unplannedSplitter', { static : false }) unplannedSplitterComponent!: BryntumSplitterComponent;

    ngAfterViewInit() {
        this.initializeComponents();
        this.setupGridStore();
        this.setupEventListeners();
        this.initializeDateField();
        this.showMap();
        this.setupDragHelper();
    }

    private setupGridStore = (): void => {
        this.grid.store = this.project.eventStore.chain((eventRecord : Task) => !eventRecord.assignments.length);
        this.grid.store.sort('name');
    };

    private initializeComponents = (): void => {
        this.schedulerPro      = this.schedulerProComponent.instance;
        this.project           = this.projectComponent.instance;
        this.grid              = this.gridComponent.instance;
        this.unplannedSplitter = this.unplannedSplitterComponent.instance;
    };

    private setupEventListeners = (): void => {
        this.schedulerPro.on({
            eventClick        : this.onEventClick,
            afterEventSave    : this.onAfterEventSave,
            unscheduledToggle : this.onUnscheduledToggle
        });

        this.project.assignmentStore.on({
            change : () => {
                (this.grid.store as StoreChainedClass).fillFromMaster();
            }
        });

        this.schedulerPro.widgetMap['dateField'].on('change', this.onDateFieldChange);
        this.schedulerPro.widgetMap['newEventButton'].on('click', this.onNewEventClick);
        this.schedulerPro.widgetMap['filterByName'].on('change', this.onFilterChange);
        this.schedulerPro.widgetMap['toggleUnscheduled'].on('change', this.onToggleUnscheduled);

        this.grid.on({
            cellClick : this.onCellClick
        });

        this.unplannedSplitter.on({
            splitterExpandClick   : this.onUnplannedSplitterToggle,
            splitterCollapseClick : this.onUnplannedSplitterToggle
        });
    };

    private initializeDateField = (): void => {
        (this.schedulerPro.widgetMap['dateField'] as DateField).value = this.schedulerPro.startDate;
    };

    private setupDragHelper = (): void => {
        this.dragHelper = new Drag({
            grid         : this.grid,
            schedule     : this.schedulerPro,
            constrain    : false,
            outerElement : this.grid.element
        } as DragHelperConfig);
    };

    private detectWebGL = (): boolean => {
        try {
            const canvas = document.createElement('canvas');
            document.body.appendChild(canvas);
            const supported = Boolean(canvas.getContext('webgl'));
            canvas.remove();
            return supported;
        }
        catch (e) {
            return false;
        }
    };

    private showMap = (): void => {
        if (this.detectWebGL()) {
            this.initializeMapPanel();
            this.showMapboxLicenseToast();
        }
        else {
            this.showWebGLError();
        }
    };

    private initializeMapPanel = (): void => {
        this.mapPanel = new MapPanel({
            ref         : 'map',
            appendTo    : 'content',
            flex        : 3,
            collapsible : true,
            header      : false,
            eventStore  : this.schedulerPro.eventStore,
            timeAxis    : this.schedulerPro.timeAxis,
            listeners   : {
                markerclick : this.onMarkerClick.bind(this)
            }
        });
    };

    private onMarkerClick = async({ eventRecord }: { eventRecord: Task }): Promise<void> => {
        if (eventRecord.resources.length > 0) {
            await this.schedulerPro.scrollEventIntoView(eventRecord, { animate : true, highlight : true });
            this.schedulerPro.selectedEvents = [eventRecord];
        }
        else {
            await (this.grid as unknown as SubGrid).expand(true);
            (this.schedulerPro.widgetMap['toggleUnscheduled'] as SlideToggle).value = true;
            this.grid.scrollRowIntoView(eventRecord, { animate : true, highlight : true });
        }
    };

    onUnplannedSplitterToggle = ({ eventName }: { eventName: string }): void => {
        const slideToggle = this.schedulerPro.widgetMap['toggleUnscheduled'] as SlideToggle;
        slideToggle.value = eventName === 'splitterCollapseClick';
    };

    onEventClick: SchedulerProListenersTypes['eventClick'] = ({ eventRecord }) => {
        const task = eventRecord as Task;
        if (task.marker) {
            this.mapPanel?.showTooltip(task, true);
        }
    };

    onAfterEventSave: SchedulerProListenersTypes['afterEventSave'] = ({ eventRecord }) => {
        const task = eventRecord as Task;
        if (task.marker) {
            this.mapPanel?.scrollMarkerIntoView(task);
        }
    };

    onNewEventClick: ButtonListenersTypes['click'] = () => {
        const newTask = new this.project.eventStore.modelClass({
            startDate : this.schedulerPro.startDate
        });

        this.schedulerPro.editEvent(newTask);
    };

    onDateFieldChange: DateFieldListenersTypes['change'] = ({ value, userAction }) => {
        if (userAction) {
            const
                startTime = DateHelper.add(value, 8, 'hour'),
                endTime   = DateHelper.add(value, 20, 'hour');

            this.schedulerPro.setTimeSpan(startTime, endTime);
        }
    };

    onFilterChange: TextFieldListenersTypes['change'] = ({ value }) => {
        const escapedValue = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

        this.schedulerPro.eventStore.filter({
            filters : (event: Task) => new RegExp(escapedValue, 'i').test(event.name),
            replace : true
        });
    };

    onToggleUnscheduled: SlideToggleListenersTypes['change'] = ({ value }) => {
        this.schedulerPro.trigger('unscheduledToggle', { value });
    };

    onUnscheduledToggle = ({ value } : { value: boolean }) => {
        this.grid.toggleCollapsed(!value);
    };

    onCellClick: GridListenersTypes['cellClick'] = ({ record }) => {
        const task = record as Task;
        if (task.marker) {
            this.mapPanel?.showTooltip(task, true);
        }
    };

    private showWebGLError = (): void => {
        Toast.show({
            html    : 'ERROR! Can not show show maps. WebGL is not supported!',
            color   : 'b-red',
            style   : 'color:white',
            timeout : 0
        });
    };

    private showMapboxLicenseToast = (): void => {

        Toast.show({
            html : `
                <p>This demo uses the awesome <b>MapBox GL JS</b> library (<a href="https://github.com/mapbox/mapbox-gl-js">GitHub</a>,
                <a href="https://github.com/mapbox/mapbox-gl-js/blob/main/LICENSE.txt">License</a>).</p>
                <p>It is a separately licensed 3rd party library not part of the Bryntum product,<br>if you plan to use it
                in your app you must use your own access token.</p>
            `,
            timeout : 20000
        });
    };
}

<!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
<bryntum-demo-header></bryntum-demo-header>

<bryntum-scheduler-pro-project-model
    #project
    [autoLoad]="projectProps.autoLoad!"
    [loadUrl]="projectProps.loadUrl!"
    [resourceStore]="projectProps.resourceStore!"
    [eventStore]="projectProps.eventStore!"
    [validateResponse]="projectProps.validateResponse!">
</bryntum-scheduler-pro-project-model>

<div id="content" class="b-side-by-side">
    <bryntum-scheduler-pro
        #schedulerPro
        [flex]="8"
        [project]="project"
        [startDate]="schedulerProProps.startDate!"
        [endDate]="schedulerProProps.endDate!"
        [taskEditFeature]="schedulerProProps.taskEditFeature!"
        [eventBufferFeature]="schedulerProProps.eventBufferFeature!"
        [stripeFeature]="schedulerProProps.stripeFeature!"
        [allowOverlap]="schedulerProProps.allowOverlap!"
        [rowHeight]="schedulerProProps.rowHeight!"
        [barMargin]="schedulerProProps.barMargin!"
        [collapsible]="schedulerProProps.collapsible!"
        [collapsed]="schedulerProProps.collapsed!"
        [header]="schedulerProProps.header!"
        [eventColor]="schedulerProProps.eventColor!"
        [eventStyle]="schedulerProProps.eventStyle!"
        [columns]="schedulerProProps.columns!"
        [viewPreset]="schedulerProProps.viewPreset!"
        [resourceImagePath]="schedulerProProps.resourceImagePath!"
        [tbar]="tbar!"
        [eventRenderer]="schedulerProProps.eventRenderer!"
    >
    </bryntum-scheduler-pro>
    <bryntum-splitter #mapSplitter [showButtons]="true"></bryntum-splitter>
</div>
<bryntum-splitter #unplannedSplitter [showButtons]="'end'" *ngIf="grid"></bryntum-splitter>
<bryntum-grid
    #grid
    [rowHeight]                  = "gridProps.rowHeight!"
    [disableGridRowModelWarning] = "gridProps.disableGridRowModelWarning!"
    [collapsible]                = "gridProps.collapsible!"
    [header]                     = "gridProps.header!"
    [minHeight]                  = "gridProps.minHeight!"
    [selectionMode]              = "gridProps.selectionMode!"
    [stripeFeature]              = "gridProps.stripeFeature!"
    [sortFeature]                = "gridProps.sortFeature!"
    [columns]                    = "gridProps.columns!"
    [collapsed]                  = "gridProps.collapsed!"
    [flex]                       = "gridProps.flex!"
></bryntum-grid>
