// src/lib/schedulerpro-6.3.3-trial/examples-scheduler/frameworks/vue/javascript/drag-between-schedulers/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <!-- BryntumDemoHeader component is used for Bryntum example styling only and can be removed -->
        <bryntum-demo-header />
        <bryntum-scheduler
            ref="scheduler1"
            v-bind="scheduler1Config"
        />
        <bryntum-splitter />
        <bryntum-scheduler
            ref="scheduler2"
            v-bind="scheduler2Config"
        />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumSplitter,
    BryntumDemoHeader
} from '@bryntum/schedulerpro-vue';
import { scheduler1Config, scheduler2Config } from './AppConfig';

export default {
    name : 'App',

    components : {
        BryntumDemoHeader,
        BryntumScheduler,
        BryntumSplitter
    },

    mounted() {
        // make schedulers partnered so that they scroll together
        this.$refs.scheduler2.instance.addPartner(this.$refs.scheduler1.instance);
    },

    data() {
        return {
            scheduler1Config,
            scheduler2Config
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// src/lib/schedulerpro-6.3.3-trial/examples-scheduler/frameworks/react-vite/eventeditor-combos/src/App.tsx
import { FunctionComponent, useRef } from 'react';
import { BryntumDemoHeader, BryntumScheduler } from '@bryntum/schedulerpro-react';
import { schedulerProps } from './AppConfig';
import './App.scss';

const App: FunctionComponent = () => {

    const scheduler = useRef<BryntumScheduler>(null);

    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <BryntumScheduler
                ref = {scheduler}
                {...schedulerProps}
            />
        </>
    );
};

export default App;
