// src/lib/schedulerpro-6.3.3-trial/examples/frameworks/react-vite/drag-unplanned-tasks/src/components/GridToolbar.tsx
import { RefObject, useCallback, useEffect, useState } from 'react';
import { BryntumGrid, BryntumToolbar } from '@bryntum/schedulerpro-react';
import { Grid } from '@bryntum/schedulerpro';

type GridToolbarProps = {
    gridRef?: RefObject<BryntumGrid>
}

const GridToolbar = (props: GridToolbarProps) => {
    const { gridRef } = props;

    const [grid, setGrid] = useState<Grid>();

    useEffect(() => {
        setGrid(gridRef!.current!.instance);
    }, [gridRef]);

    const onExpandAll = useCallback(() => {
        grid!.expandAll();
    }, [grid]);

    const onCollapseAll = useCallback(() => {
        grid!.collapseAll();
    }, [grid]);

    return <BryntumToolbar
        items={[
            {
                type : 'widget',
                tag  : 'strong',
                html : 'Unplanned appointments',
                flex : 1
            },
            {
                type    : 'button',
                icon    : 'b-fa b-fa-angle-double-down',
                ref     : 'expand-all', // for testing purpose
                cls     : 'b-transparent',
                tooltip : 'Expand all groups',
                onClick : onExpandAll
            },
            {
                type    : 'button',
                icon    : 'b-fa b-fa-angle-double-up',
                ref     : 'collapse-all', // for testing purpose
                cls     : 'b-transparent',
                tooltip : 'Collapse all groups',
                onClick : onCollapseAll
            }
        ]}
    />;
};

export default GridToolbar;

// src/lib/schedulerpro-6.3.3-trial/examples/frameworks/vue-3-vite/drag-unplanned-tasks/src/components/GridToolbar.vue
<script setup lang="ts">
import { BryntumToolbar } from '@bryntum/schedulerpro-vue-3';

const props = defineProps({
    gridRefFn : {
        type    : Function,
        default : () => {}
    }
});

const onExpandAll = () => {
    const grid = props.gridRefFn().value.instance.value;
    grid!.expandAll();
};

const onCollapseAll = () => {
    const grid = props.gridRefFn().value.instance.value;
    grid!.collapseAll();
};

const GridTbarConfig = {
    items : [
        {
            type : 'widget',
            tag  : 'strong',
            html : 'Unplanned appointments',
            flex : 1
        },
        {
            icon     : 'b-fa b-fa-angle-double-down',
            ref      : 'expand-all', // for testing purpose
            cls      : 'b-transparent',
            tooltip  : 'Expand all groups',
            onAction : onExpandAll
        },
        {
            icon     : 'b-fa b-fa-angle-double-up',
            ref      : 'collapse-all', // for testing purpose
            cls      : 'b-transparent',
            tooltip  : 'Collapse all groups',
            onAction : onCollapseAll
        }
    ]
};

</script>

<template>
    <bryntum-toolbar
        v-bind="GridTbarConfig"
    />
</template>
