// src/lib/schedulerpro-6.3.3-trial/examples-scheduler/frameworks/angular/drag-from-grid/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { environment } from './environments/environment';
import { Toast } from '@bryntum/schedulerpro';
import { AppModule } from './app/app.module';

if (environment.production) {
    enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.error(err));


Toast.show({
    html    : `<p>This demo uses the <a href="https://bryntum.com/products/grid/">Bryntum Grid</a> component which is licensed separately.</p>`,
    timeout : 10000
});

// src/lib/schedulerpro-6.3.3-trial/examples-scheduler/frameworks/react-vite/drag-from-grid/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { Toast } from '@bryntum/schedulerpro';
import App from './App';

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
    <React.StrictMode>
        <App/>
    </React.StrictMode>
);

// <test>
!document.location.search.includes('test') &&
// </test>
Toast.show({
    html    : `<p>This demo uses the <a href="https://bryntum.com/products/grid/">Bryntum Grid</a> component which is licensed separately.</p>`,
    timeout : 10000
});
