// src/lib/schedulerpro-6.3.3-trial/examples/frameworks/angular/drag-unplanned-tasks/src/main.ts
import { ViewEncapsulation } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { Toast } from '@bryntum/schedulerpro';
import { AppModule } from './app/app.module';

platformBrowserDynamic().bootstrapModule(AppModule, {
    defaultEncapsulation : ViewEncapsulation.None
}).catch(err => console.error(err));


Toast.show({
    html : `<p>This demo uses the <a href='https://bryntum.com/products/grid/'>Bryntum Grid</a> component which is licensed separately.</p>
    `,
    timeout : 10000
});

// src/lib/schedulerpro-6.3.3-trial/examples/frameworks/react-vite/drag-unplanned-tasks/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { Toast } from '@bryntum/schedulerpro';

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
    <React.StrictMode>
        <App/>
    </React.StrictMode>
);

// <test>
!document.location.search.includes('test') &&
// </test>
Toast.show({
    html : `<p>This demo uses the <a href='https://bryntum.com/products/grid/'>Bryntum Grid</a> component which is licensed separately.</p>
    `,
    timeout : 10000
});
