// src/lib/schedulerpro-6.3.3-trial/examples-scheduler/frameworks/vue-3-vite/event-rendering/src/App.vue
<script setup lang="ts">
import { BryntumDemoHeader, BryntumScheduler } from '@bryntum/schedulerpro-vue-3';
import { schedulerProps } from './AppConfig';
import './App.scss';
</script>

<template>
    <!-- BryntumDemoHeader component is used for Bryntum example only and can be removed -->
    <bryntum-demo-header />
    <bryntum-scheduler v-bind="schedulerProps" />
</template>

<style>
  @import './App.scss';
</style>

// src/lib/schedulerpro-6.3.3-trial/examples-scheduler/frameworks/react-vite/react-events/src/App.tsx
import { type FunctionComponent } from 'react';
import { BryntumDemoHeader, BryntumScheduler } from '@bryntum/schedulerpro-react';
import { schedulerProps } from './AppConfig';

import './App.scss';

const App : FunctionComponent = () => {

    return (
        <>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader/>
            <BryntumScheduler {...schedulerProps} />
        </>
    );

};

export default App;
